#!/usr/bin/env python
"""Statically verify a workspace generated by build_taming_absgs.py.

This deliberately does not import PyTorch or compile CUDA. It is safe to run
immediately after building on Kaggle, before installing CUDA extensions.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify a generated Taming-AbsGS workspace.")
    parser.add_argument("--hybrid-root", required=True, help="Output directory from build_taming_absgs.py.")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(argv)
    root = Path(args.hybrid_root).expanduser().resolve()
    if not root.is_dir():
        raise FileNotFoundError(f"--hybrid-root must be an existing directory: {root}")

    checks = {
        "arguments/__init__.py": ["densify_grad_abs_threshold"],
        "scene/gaussian_model.py": [
            "xyz_gradient_accum_abs",
            "abs_grad_qualifiers",
            "all_splits = torch.logical_and(split_qualifiers, abs_grad_qualifiers)",
            "restore_absolute_opacity_mode",
        ],
        "gaussian_renderer/__init__.py": ["(pc.get_xyz.shape[0], 4)"],
        "train.py": [
            "abs_grad_threshold=opt.densify_grad_abs_threshold",
            "if first_iter >= args.ho_iteration:",
            "gaussians.restore_absolute_opacity_mode()",
            "torch.load(checkpoint, weights_only=False)",
        ],
        "submodules/diff-gaussian-rasterization/rasterize_points.cu": ["zeros({P, 4}"],
        "submodules/diff-gaussian-rasterization/cuda_rasterizer/backward.cu": [
            "Register_dL_dmean2D_abs_x",
            "fabs(dL_dG * dG_ddelx * ddelx_dx)",
            "float4* dL_dmean2D",
        ],
        "TAMING_ABSGS_BUILD_INFO.md": ["Taming's score-based budgeted densification"],
    }

    failures: list[str] = []
    for relative_path, markers in checks.items():
        path = root / relative_path
        if not path.is_file():
            failures.append(f"missing file: {relative_path}")
            continue
        content = path.read_text(encoding="utf-8")
        missing = [marker for marker in markers if marker not in content]
        if missing:
            failures.append(f"{relative_path}: missing {', '.join(missing)}")

    if failures:
        print("Taming-AbsGS verification failed:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        raise SystemExit(1)

    print("Taming-AbsGS static verification passed.")
    print(f"Hybrid workspace: {root}")
    print("Validated: AbsGS gradient channels, split qualifier, Taming budget path, and CUDA patch markers.")


if __name__ == "__main__":
    main()
